DROP TABLE IF EXISTS USER_ACCOUNT;

CREATE TABLE USER_ACCOUNT (
    ID INT,
    USERNAME VARCHAR(255),
    PASSWORD VARCHAR(255)
);

INSERT INTO USER_ACCOUNT (USERNAME, PASSWORD) VALUES ('qwerty@qwerty.com', 'qwerty');